kubernetes:
  host: https://kubernetes.default

helloworld:
  namespace: default
  image:
    name: shining-medium-354919/helloworld:5ed2d73
    tag: latest
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress