apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  # you can only have one ConfigConnectorContext per namespace
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: gke-deployer-iap-bastion-host
spec:
  googleServiceAccount: "config-connector@gke-deployer-iap-bastion-host.iam.gserviceaccount.com"