apiVersion: templates.gatekeeper.sh/v1beta1 
kind: ConstraintTemplate 
metadata: 
  name: k8sresourcequota 
spec:
  crd:
    spec:
      names:
        kind: k8sResourceQuota
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sresourcequota

        violation[{"msg": msg}] {
          input.review.kind.kind == "Pod"
          requestns := input.review.object.metadata.namespace
          rqs := {e | e := data.inventory.namespace[requestns]["v1"]["ResourceQuota"][_]}
          count(rqs) == 0
          msg := sprintf("container <%v> could not be created because the <%v> namespace does not have ResourceQuotas defined", [input.review.object.metadata.name,input.review.object.metadata.namespace])
          }
