apiVersion: templates.gatekeeper.sh/v1beta1 
kind: ConstraintTemplate 
metadata: 
  name: k8sresourcequota 
spec:
  crd:
    spec:
      names:
        kind: k8sResourceQuota
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sresourcequota

        violation[{"msg": msg}] {
          input.request.kind.kind == "Pod"
          requestns := input.request.object.metadata.namespace
          not data.inventory.namespace[requestns]["v1"]["ResourceQuota"][requestns]
          # msg := sprintf("Input <%v>", [data.inventory.namespace[config-sync-test]])
          msg := sprintf("container <%v> could not be created because the <%v> namespace does not have ResourceQuotas defined", [input.request.object.metadata.name,input.request.object.metadata.namespace])
          }
