apiVersion: v1
kind: ResourceQuota
metadata:
  name: config-sync-test-quota
  namespace: config-sync-test
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi